### ISSUE TITLE
CSV File Naming 

### ISSUE THREAD

**Issue by MatthewTDuff** [rsmith52/Testing-Data-Analyzer#2]
When opening a .csv file, you need to name it first in the text box, and then hit enter before clicking the open button

**Comment by BoClow** [comment]
Severity: Critical
Description: The instructions are to click “Open .CSV”, on click nothing happens. A file selector only appears if we enter any sort of text in the textbox to the left of the button (Note: ENTER does not need to be hit). Only later do we realize that what we enter here is the name of the categorization. We suggest a placeholder or hint to display this is a name field.

**Comment by rsmith52** [comment]
Updated instructions on the page to explain a name has to be entered
