### ISSUE TITLE
PDF output files not produced

### ISSUE THREAD

**Issue by BoClow** [rsmith52/Testing-Data-Analyzer#6]
Severity: Blocker
Description: The instructions mention PDF files can be found in the “pdf” folder after click of “Output Metrics .pdf”. After a message of “Output metrics successful” the folder is empty and no pdf file is output. We also attempted this with a "pdfs" folder, still no output. No output to the user is displayed, it would be helpful to display some text output to the user.
Note this happens on ALL test datasets

**Comment by rsmith52** [comment]
This was a mistake on our README at the time, pdfs were being written to the main folder. They will now output to the pdfs folder as expected
