### ISSUE TITLE
Error on Merge Datasets

### ISSUE THREAD

**Issue by BoClow** [rsmith52/Testing-Data-Analyzer#7]
Severity: Critical
Description: After click of “Merge Datasets” with provided test data sets 1 & 2 we received this 
 output: “Dataset Merge Failed; an exception occurred"
java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [LObjects.Case;

Note: this occurred with ALL datasets

**Comment by rsmith52** [comment]
Fixed merge error by getting updated code from UI that we missed updating on the main testing branch
