### ISSUE TITLE
Cannot open output .cat file

### ISSUE THREAD

**Issue by BoClow** [rsmith52/Testing-Data-Analyzer#8]
Severity: Critical

Description: On click of output .cat file we receive this error: The File is invalid for use as the following: Security Certificate. This may be a Windows specific error.
These files are also unable to be opened on mac, though it is because there is no application which is able to open it (it is an unknown file type).

**Comment by rsmith52** [comment]
These files are not meant to be openable. They are serialized java objects written to file. .cat is used on windows as a file type which is why that error message comes up on windows. They can be written and read by the program, and are not meant to be accessed outside by the user
