### ISSUE TITLE
CSV Output Failure on Test Data Set #2 and #3

### ISSUE THREAD

**Issue by BoClow** [rsmith52/Testing-Data-Analyzer#9]
Severity: Critical
Description: After creating output successfully on dataset 1, when trying to create output.csv on Dataset #2 and #3, the only response is “CSV Output Failed”. After further look, this happens when the .csv from dataset 1 is opened in excel. The viewing of dataset 1 data should not stop the creation of other datasets. There could also be a message stating to the user that this is why the output failed.

**Comment by rsmith52** [comment]
This was caused by csv files being outputted all with the same name, so if one was in use, it couldn't be overwritten when a new file with the same name was opened to be created. csvs now use unique names like pdfs.
